sudo: required
services: 
  - docker

before_install:
  - docker build -t violetguo/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true violetguo/docker-react npm run test -- --coverage

  