FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# optional b/c of the mapping
# keeping it b/c docker compose is not used
# this line keeps it working without docker compose
COPY . . 

CMD ["npm", "run", "start"]
